name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test Shard
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, crystal: 1.12.1 }
          - { os: ubuntu-20.04, crystal: 1.11.2 }
          - { os: ubuntu-20.04, crystal: 1.10.1 }
          - { os: ubuntu-20.04, crystal: 1.9.2 }
          - { os: ubuntu-20.04, crystal: 1.8.2 }
          - { os: ubuntu-20.04, crystal: 1.7.3 }
          - { os: ubuntu-20.04, crystal: 1.6.2 }
          - { os: ubuntu-20.04, crystal: 1.5.1 }
          - { os: ubuntu-20.04, crystal: 1.4.1 }
          - { os: ubuntu-22.04, crystal: 1.12.1 }
          - { os: ubuntu-22.04, crystal: 1.11.2 }
          - { os: ubuntu-22.04, crystal: 1.10.1 }
          - { os: ubuntu-22.04, crystal: 1.9.2 }
          - { os: ubuntu-22.04, crystal: 1.8.2 }
          - { os: ubuntu-22.04, crystal: 1.7.3 }
          - { os: ubuntu-22.04, crystal: 1.6.2 }
          - { os: ubuntu-22.04, crystal: 1.5.1 }
          - { os: ubuntu-22.04, crystal: 1.4.1 }
          - { os: macOS-latest, crystal: 1.12.1 }
          - { os: macOS-latest, crystal: 1.11.2 }
          - { os: macOS-latest, crystal: 1.10.1 }
          - { os: macOS-latest, crystal: 1.9.2 }
          - { os: macOS-latest, crystal: 1.8.2 }
          - { os: macOS-latest, crystal: 1.7.3 }
          - { os: macOS-latest, crystal: 1.6.2 }
          - { os: macOS-latest, crystal: 1.5.1 }
          - { os: macOS-latest, crystal: 1.4.1 }
    runs-on: ${{matrix.os}}
    steps:
      - name: 'Prepare Ubuntu 22.04 ENV'
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt install pdftk

      - name: 'Prepare Ubuntu 20.04 ENV'
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt install pdftk

      - name: 'Prepare MacOS ENV'
        if: matrix.os == 'macOS-latest'
        run: |
          brew install pdftk-java

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        run: |
          shards install
          crystal run ./spec/*_test.cr
          crystal tool format && git diff --exit-code
