name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: Test Shard
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, crystal: 1.6.1 }
          - { os: ubuntu-20.04, crystal: 1.5.1 }
          - { os: ubuntu-20.04, crystal: 1.4.1 }
          - { os: ubuntu-20.04, crystal: 1.3.2 }
          - { os: ubuntu-20.04, crystal: 1.2.1 }
          - { os: ubuntu-20.04, crystal: 1.1.1 }
          - { os: ubuntu-20.04, crystal: 1.0.0 }
          - { os: ubuntu-20.04, crystal: 0.36.1 }
          - { os: ubuntu-22.04, crystal: 1.6.1 }
          - { os: ubuntu-22.04, crystal: 1.5.1 }
          - { os: ubuntu-22.04, crystal: 1.4.1 }
          - { os: ubuntu-22.04, crystal: 1.3.2 }
          - { os: ubuntu-22.04, crystal: 1.2.1 }
          - { os: ubuntu-22.04, crystal: 1.1.1 }
          - { os: ubuntu-22.04, crystal: 1.0.0 }
          - { os: ubuntu-22.04, crystal: 0.36.1 }
          - { os: macOS-latest, crystal: 1.6.1 }
          - { os: macOS-latest, crystal: 1.5.1 }
          - { os: macOS-latest, crystal: 1.4.1 }
          - { os: macOS-latest, crystal: 1.3.2 }
          - { os: macOS-latest, crystal: 1.2.1 }
          - { os: macOS-latest, crystal: 1.1.1 }
          - { os: macOS-latest, crystal: 1.0.0 }
          - { os: macOS-latest, crystal: 0.36.1 }
    runs-on: ${{matrix.os}}
    steps:
      - name: 'Prepare Ubuntu 22.04 ENV'
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt install pdftk

      - name: 'Prepare Ubuntu 20.04 ENV'
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt install pdftk
      
      - name: 'Prepare Ubuntu 18.04 ENV'
        if: matrix.os == 'ubuntu-18.04'
        run: |
          wget http://launchpadlibrarian.net/475142792/pdftk-java_3.0.9-1_all.deb
          sudo apt install default-jre-headless libcommons-lang3-java libbcprov-java
          sudo dpkg -i pdftk-java_3.0.9-1_all.deb
      - name: 'Prepare MacOS ENV'
        if: matrix.os == 'macOS-latest'
        run: |
          brew install pdftk-java

      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          shards install
          crystal run ./spec/*_test.cr
          crystal tool format && git diff --exit-code
